config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"


  resources :books
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }



def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpeg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(id: current_user)
  end
  def after_sign_out_path_for(resource)
    root_path
  end

  add_flash_types :success, :info, :warning, :danger


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      @users = User.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @users = User.all
    @user = User.find_by(id: @book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to  books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
       render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books', notice: "Book was successfully destroyed."
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
     redirect_to example_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @book = Book.new
    @books = @user.books
  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.index(user_params)
    if @user.save
      redirect_to root_path, success: 'Welcome! You have signed up successfully.'
    end
  end



  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Signed out successfully.'
  end



  private

  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
  <div class="col-md-3" >
     <h2>User info</h2>
     <table class="table table-striped">
        <thead>
          <%= image_tag @user.get_profile_image(100,100) %>
          <tr>
            <th>name</th>
          	<th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </thead>
        <br>
    </table>
      <div class="row">
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-sm btn-block " do %><i class="fas fa-user-cog"></i><% end %>
      </div>

      <h2>New book</h2>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

        <%= form_with model: (Book.new) do |f| %>
          <%= f.label :Title %><br/>
          <%= f.text_field :title, class: "form-control book_title" %>
          <br>
          <%= f.label :Opinion %><br/>
          <%= f.text_area :body, class: "form-control book_body" %>
            <br>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this book from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

      <%= form_with(model: @book, local: true) do |f| %>
          <%= f.label :Title %><br>
          <%= f.text_field :title, class: "form-control book_title" %>
          <br>
          <%= f.label :Opinion %><br>
          <%= f.text_area :body, class: "form-control book_body" %>
          <br>
          <%= f.submit 'Update Book', class: "btn btn-success"%>
      <% end %>
      <br>

      <%= link_to 'Show', @book %> |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'book', users: @users %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%  @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <% if book.user.profile_image.attached? %>
                      <%= image_tag book.user.profile_image, size: "100x100" %>
                    <% else %>
                      <%= image_tag 'no_image', size: "100x100" %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                 <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'book', users: @users %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table ">
        <tbody>
            <tr>
              <td>
                <% if @book.user.profile_image.attached? %>
                  <%= image_tag @book.user.profile_image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %><br>
                <%= link_to @book.user.name, user_path(@book.user_id) %>
              </td>
              <td><%=link_to @book.title %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success" %></td>
              <td><%= link_to "Destroy", @book, method: :delete, data: { confirm: '本当に消しますか?' }, class: "btn btn-danger" %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
</div>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <strong><i class="fas fa-book"></i>
      Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
		<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6" >
      <div class="top-text">
				<h1>Welcome to
				  <i class="fas fa-book"></i>
				  <b>Bookers!!</b>
				</h1>
				<p>In
				  <i class="fas fa-book"></i>
				  <b>Bookers</b>,<br>
				  	you can share and exchange your opinions , inpresiions , and emotions<br>
				  	about various books!
				</p>
		  </div>
			<div class="row">
		      <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
			</div>
			<div class="row">
			  <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: "navbar-brand" do %>
            <span>Bookers</span>
          <% end %>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown"  >
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(id: current_user), class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p id="notice">
     <%= notice %>
    </p>
    <%= yield %>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h1>User info</h1>
        <% if @user.errors.any? %>
                <%= @user.errors.count %>errors prohibited this book from being saved:
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
        <% end %>
        <%= form_with(model: @user, local: true) do |f| %>

          <div class="user-name">Name</div>
            <%= f.text_field :name %>
          <div class="user-edit-image">Image</div>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          <div class="form-body">Introduction</div>
            <%= f.text_area :introduction %><br>
          <div class="upload">
            <%= f.submit " Update User" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book', users: @users %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
            	<%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book', users: @users %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image, size: "100x100" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "100x100" %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%=link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>